# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: What A Theme
# Description of the Site
description: A customizable Jekyll portfolio theme
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: felipejcanales@outlook.com
instagram_username: FlipsTechHub
linkedin_username: felipejesuscanales
github_username:  FelipeCanales94
youtube_channel_id: UCcO8SGT94oqlYJH95_cGfFw

# Google Analytics
google-analytics: /

# Name of the Author
author-name: Felipe Canales
# URL for the Image of the Author
author-image: /assets/images/pfpic.jpg
# 60 Words About the Author
author-about: I am a Software Engineer with a strong passion for Artificial Intelligence and a dedication to leveraging cutting-edge technology to create innovative solutions. Currently, I work for American Express on the anti-money laundering team, where I am responsible for designing and implementing solutions to detect and prevent financial crimes.

Before joining American Express, I worked as a Software Engineer on the DevOps team at M&T Bank, where I honed my skills in automation and infrastructure management. Additionally, I gained valuable experience as a machine learning/data science intern at Linde plc, where I assisted in maintaining and expanding predictive models and data-driven solutions to improve operational efficiency.

I am a graduate of the University at Buffalo, where I earned both my Bachelor's and Master's degrees in Computer Science with a heavy focus on Artificial Intelligence. My passion for learning extends beyond the classroom, and I am constantly seeking new challenges and opportunities to expand my knowledge and skills. Whether it's exploring new programming languages or experimenting with emerging technologies, I am always eager to push the boundaries of what's possible and stay at the forefront of the tech industry.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/FelipeCanales94

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
